add_newline = false
format = '$directory$git_branch $character '

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
style = "#dddddd"
format = "[$path]($style)"

[git_branch]
style = "#666666"
format = " [$branch]($style)"

[character]
success_symbol = '[➤](#ffffff)'
error_symbol = '[➤](#999999)'
