theme = "solyn"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = false
true-color = true
auto-format = true
auto-save = false
bufferline = "multiple"
color-modes = true
scrolloff = 5
scroll-lines = 3
completion-trigger-len = 1
idle-timeout = 50
rulers = [80, 120]
shell = ["fish", "-c"]
end-of-line-diagnostics = "hint"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.file-picker]
hidden = false
git-ignore = true
follow-symlinks = true
deduplicate-links = true

[editor.search]
smart-case = true
wrap-around = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[keys.normal.space.e]
w = ":write"
c = ":buffer-close"
a = ":reload-all"

[keys.normal.space.f]
f = "file_picker_in_current_directory"
F = "file_picker"
g = "global_search"
b = "buffer_picker"
e = "file_explorer"
"." = ":toggle-option file-picker.git-ignore"

[keys.normal.space.g]
b = [":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"]
d = [":new", ":lang diff", ":insert-output git diff", "goto_file_start"]
x = ":reset-diff-change"

[keys.normal.space.c]
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
y = "yank_to_clipboard"

[keys.normal."\\"]
f = ":format"
w = ":toggle whitespace.render all"
s = ":toggle soft-wrap.enable"
t = ":toggle cursorline"
n = ":toggle line-number"
i = ":toggle lsp.display-inlay-hints"
r = ":toggle rulers"

[keys.select]
d = "delete_selection"

[keys.select.space]
c = "yank_to_clipboard"
v = ":clipboard-paste-replace"
